# Generated by Django 6.0.4 on 2026-04-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_company_address_remove_user_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('vendor', 'Vendor')], default='user', max_length=10),
        ),
    ]
