# Generated by Django 5.2.5 on 2026-04-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('vendor', 'Vendor'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
