# Generated by Django 6.0.4 on 2026-04-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='tour',
            name='available_seats',
            field=models.IntegerField(),
        ),
    ]
