# Generated by Django 6.0.4 on 2026-04-18 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_tour_end_date_remove_tour_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['vendor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/images/'),
        ),
    ]
