# Generated by Django 6.0.4 on 2026-04-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticket',
            old_name='admin_response',
            new_name='response',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='recipient_role',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('admin', 'Admin')], default='admin', max_length=10),
        ),
    ]
