# Generated by Django 6.0.4 on 2026-04-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='vendor',
        ),
    ]
