# Generated by Django 6.0.4 on 2026-04-12 03:37

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(validators=[bookings.models.validate_not_past]),
        ),
    ]
