# Generated by Django 6.0.4 on 2026-04-12 04:08

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_travel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, validators=[bookings.models.validate_not_past]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(auto_now_add=True, validators=[bookings.models.validate_not_past]),
        ),
    ]
