# Generated by Django 5.2.5 on 2026-04-18 06:22

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_travel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(validators=[bookings.models.validate_not_past]),
        ),
    ]
